config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :animals
  resources :categories
  resources :petshops
  resources :descontos
  resources :agendamentos
  devise_for :users

  devise_scope :user do
    get "/store/:store" => "devise/registrations#new"
  end

  root to: "pages#welcome"

  get 'destroy-logo', action: :destroy_logo, controller: 'pages'
  resources :store_steps

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)


      if user.role == "admin"
        can :create, :all
        can :update, :all
        can :destroy, :all
        can :read, :all
      else

      end

      if user.role == "user"
        can :create, Animal
        can :update, Animal
        can :destroy, Animal

      else

      end

    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user

 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :petshop
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :petshop
end

app/models/discount.rb
class Discount < ApplicationRecord
  belongs_to :discountable, polymorphic: true
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :petshop
  belongs_to :user
end

app/models/petshop.rb
class Petshop < ApplicationRecord

belongs_to :user
has_one_attached :logo
validates :title, presence: true


# seach form
def self.search(search)
    if search
      where(["cidade LIKE ?","%#{search}%"])
    else
    all
    end
end





end

app/models/plan.rb
class Plan < ApplicationRecord
 
end

app/models/plan_select.rb
class PlanSelect < ApplicationRecord
  belongs_to :user
  belongs_to :plan
end

app/models/user.rb
class User < ApplicationRecord

  has_many :animals
  has_one  :petshop
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
# User Rules
 ROLES = %i[admin user store banned]

 after_create :welcome_send

  def welcome_send
    @user = User.last
    @user.create_petshop(title: 'Titulo de sua loja')
    WelcomeMailer.welcome_send(self).deliver
  end




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome
     @petshops = Petshop.take(10)
     @store = current_user.petshop
  end

  def destroy_logo

    @store = User.all

    respond_to do |format|

      format.html
      format.json { render json: @store}

    end

  end


end

app/helpers/agendamentos_helper.rb
module AgendamentosHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

def title(page_title)
  content_for(:title) {page_title}
end

def company_name
   "Cartão Mais Pet "
end

def select_menu

  if current_user.role == "user"
  render('layouts/parts/usernav')
  else
  render('layouts/parts/storenav')
  end
end

def user_avatar

if current_user.avatar.attached? == true
image_tag(current_user.avatar, size:"150x150", class: "responsive circle align-center")
else
  require 'digest/md5'
  hash = Digest::MD5.hexdigest(current_user.email.downcase)
  image_tag("https://www.gravatar.com/avatar/#{hash}?d=mp", size:"150x150", class: "responsive circle align-center")
end

end

def petshop
   @petshop = Petshop.current_user.id
end




end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/descontos_helper.rb
module DescontosHelper
end

app/helpers/pages_helper.rb
module PagesHelper

def saudacao

  time = Time.now
  if time > time.at_beginning_of_day
    "Bom dia! " + current_user.name.capitalize
  end
  if time > time.at_midday
    "Boa tarde! " + current_user.name.capitalize
  end
  if time > time.at_midday + 6.hour
   "Boa Noite! " + current_user.name.capitalize
  end
end

 


end

app/helpers/petshops_helper.rb
module PetshopsHelper


require "correios-cep"

def ask_form

 

end

end

app/helpers/store_steps_helper.rb
module StoreStepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= company_name + yield(:title) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<%= stylesheet_link_tag    "application", :media => "all" %>
<!-- Compiled and minified JavaScript -->

<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

</head>

<body>

  <%= render 'layouts/parts/menu' %>
<div class="section"></div>

  <div class="container">

<% if flash[:notice] %>
<div id="notice" class="notify notify--success" role="alert">
  <strong><%= notice %></strong>
</div>
<% end %>
<% if flash[:alert] %>
<div id="alert" class="notify notify--danger" role="alert">
  <strong><%= alert %></strong>
</div>

<% end %>
<div class="row">
      <%= yield %>
    </div>

  </div>

  <div class="section"></div>
  <%= render 'layouts/parts/footer' %>



  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
</body>
</html>

app/views/layouts/parts/_footer.html.erb
<footer class="page-footer pet-blue">
        <div class="container">
          <div class="row">
            <div class="col l6 s12">
              <h5 class="white-text">Quem Ama Cuida</h5>
              <p class="grey-text text-lighten-4">Sistema de gerenciamento Cartão Mais Pet  </p>
            </div>
            <div class="col l4 offset-l2 s12">

            </div>
          </div>
        </div>
        <div class="footer-copyright">
          <div class="container">
          © <%=  Time.now.strftime('%Y') %> Copyright Todos os direitos reservados
          <a class="grey-text text-lighten-4 right" href="#!">www.cartaomaispet.com.br</a>
          </div>
        </div>
      </footer>

app/views/layouts/parts/_menu.html.erb
<nav class="pet-blue menu-top">
  <div class="nav-wrapper">
    <div class="container">
      <div class="col s3">
     <a href="<%= root_path %>" class="brand-logo"><%= image_tag('logo.png', size:"135x65") %></a>
      </div>


<ul id="nav-mobile" class="right hide-on-med-and-down">
           <% if user_signed_in? %>

<li>
  <a href="<%= edit_user_registration_path %>" class=" collection-item"><i class="tiny material-icons left">account_box</i> Minha Conta</a>

</li>
            <!-- <li>

              <i class="material-icons">pets</i>
            </li>
            -->
            <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn blue lighten-2") %>
            </li>

          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path, class: "btn blue lighten-2")  %>
            </li>

          <% end %>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/parts/_storenav.html.erb
  <ul class="collection with-header">
  <li class="collection-header center-align">
  <a class="modal-trigger"  href="<%= root_path %>"> <%= user_avatar %> </a>
  <h6><%= saudacao() %></h6></li>
  <li>
  <a href="<%= root_path %>" class=" collection-item"><i class="tiny material-icons left">home</i> Principal</a>
  <a href="<%= descontos_path %>" class="teal-text collection-item"><i class="tiny material-icons left">local_offer</i> Criar Descontos</a>
  <a href="<%= petshops_path %>" class="teal-text collection-item"><i class="tiny material-icons left">favorite</i>Rede Credenciadas</a>
  <a href="<%= animals_path %>" class="teal-text collection-item"><i class="tiny material-icons left">pets</i> Meu Pets</a>
  <a href="<%= agendamentos_path %>" class="teal-text collection-item"><i class="tiny material-icons left">date_range</i> Agendamentos</a>

  </ul>

app/views/layouts/parts/_usernav.html.erb
<ul class="collection with-header">
  <li class="collection-header center-align">
    <a class="modal-trigger" href="<%= root_path %>">  <%= user_avatar %> </a>
      <h5><%= saudacao() %></h5></li>
   <li>

     <a href="<%= root_path %>" class=" collection-item"><i class="tiny material-icons left">home</i>Principal</a>
     <a href="<%= descontos_path %>" class="teal-text collection-item"><i class="tiny material-icons left">local_offer</i> Meus Descontos</a>
     <a href="<%= petshops_path %>" class="teal-text collection-item"><i class="tiny material-icons left">business</i>Rede Credenciadas</a>
     <a href="<%= animals_path %>" class="teal-text collection-item"><i class="tiny material-icons left">pets</i> Meu Pets</a>
     <a href="<%= agendamentos_path %>" class="teal-text collection-item"><i class="tiny material-icons left">perm_contact_calendar</i> Agendamentos</a>
     <a href="#" class="teal-text collection-item"><i class="tiny material-icons left">credit_card</i> Assinatura</a>


</ul>

app/views/pages/module/_liststore.html.erb
    <ul class="collection">
    <% @petshops.each do |p| %>

      <li class="collection-item">



        <h4 class="title"><%= p.title %></h4>
        <h4 class="right red-text"><i class=" material-icons">local_offer</i><%= Faker::Number.between(10,70) %></h4>
        <div class="row valign-wrapper">
          <div class="col s6">

            <%=


image_tag ('https://picsum.photos/300/300/?random'),
              class: "left circle responsive-img" %>
          </div>

          <span class="right">
          <%= truncate( p.descricao, length:180 ) %>
    <p></p>
      <a class="btn waves-effect waves-light  blue " href="<%= root_url %>petshops/<%= p.id %>"><i class="material-icons left">launch</i> Acessar </a>
          </span>
        </div>

      </li>



      <% end %>

app/views/pages/module/_search.html.erb
 <form action="#" method="POST">
   <h4>Buscar</h4>
<p></p>
<div class="row">


      <div class="input-field col s8 m12">
        <input id="icon_prefix" type="text" class="validate" placeholder="Pesquisar serviço ou produtos" >
        <label for="icon_prefix">Busque por:</label>
      </div>
      <div class="input-field col s6 m4">
         <i class="material-icons prefix">date_range</i>
         <input type="text" class="datepicker" placeholder="Selecione uma data">
      </div>

       <div class="input-field col s6 m4">

           <select>
             <option value="" disabled selected>Selecione</option>
             <option value="1">Manhã</option>
             <option value="2">Tarde</option>

             </select>
             <label>Materialize Select</label>

       </div>



 </div>

   <button type="submit" class="btn blue lighten-2 "> <i class="material-icons left">search</i>Buscar</button>
 </form>

app/views/pages/module/_store_start.html.erb
<table class="striped">
  <thead>
    <tr>
      <th data-field="titulo"> Sua petshop</th>

<% if @store.cidade.blank? %>
<span class="red-text">Por favor, preencha o campo: <b>CIDADE</b>.</span>
<% end %>
    </tr>
  </thead>

  <tbody>


<tr>

 <td rowspan="5" ><%  if @store.logo.attached? %>

                <%=  image_tag(@store.logo, size:"280x180", class: "responsive") %>
                       <%=  link_to('Deletar', destroy_logo_path) %>
                  <%  else %>
                      Ainda sem imagem
                    <%  end %></td>


</tr>

    <tr>
      <td> <b>Titulo de sua Loja:</b></td>
      <td><%= @store.title %></td>
    </tr>
    <tr>
      <td> <b>Endereço:</b></td>
      <td><%= @store.address %>  </td>
      </tr>
    <tr>
      <td>
        <b> CEP:</b>
      </td>
        <td> <%= @store.cep %> </td>
    </tr>
    <tr>
      <td> <b>Estado:</b></td>
      <td><%= @store.estado %></td>
    </tr>
    <tr>
      <td> <b>Cidade:</b></td>
      <td><%= @store.cidade %></td>
    </tr>
    <tr>
      <td> <b>Telefone:</b></td>
      <td><%= @store.phone %></td>
    </tr>
  </tbody>
</table>
<p></p>
<div class="col s6 m6 l6">

<%= link_to "<i class='material-icons left'>create</i> Editar".html_safe, edit_petshop_path(@store.id), class: "btn weves-effect waves-light blue lighten-2" %>
</div>

app/views/pages/welcome.html.erb
<%= title(" #{current_user.name} #{current_user.last_name} Dashboard"  ) %>
<div class="section"></div>

<!-- left col  -->

  <div class="col s12 m3">


  <%=  select_menu()  %>
  <!-- Element Showed -->




  </div> <!-- end left col -->

<!-- col right -->


  <div class="col s12 m9">
<h3>Olá <%= current_user.name %></h3>

  <%= render "shered/dashboard" %>

  </div>
<div class="section"></div>

<div class="col s12 m9">



</div>





<!-- end col right  -->

app/views/shered/_apresentacao.html.erb
<div class="fixed-action-btn">
  <a id="menu" class="waves-effect waves-light btn btn-floating" ><i class="material-icons">menu</i></a>

</div>

<% if flash[:notice] %>
  <div class="tap-target  lighten-4 teal" data-target="menu">
    <div class="tap-target-content">
      <h5>Olá <%= current_user.name %> Bem-vindo ao Cartão Mais Pet</h5>
      <p>Aqui você tem vantagem e desconto para seu Pet</p>
    </div>
  </div>
<% end %>

app/views/shered/_dashboard.html.erb
<% if current_user.role == "store" %>
<!-- for store dashboard -->
<%= render('pages/module/store_start') %>

<% end %> <!-- end current user store -->

<% if current_user.role == "user" %>
<!-- for User dashboard -->
<div class="col s12 m6">
    <div class="card cyan darken-2">
        <div class="card-action  cyan darken-4 white-text">
          <span class="card-title"><i class="material-icons">add</i> Total de Desconto</span>
        </div>
      <div class="card-content white-text">
        <h4> R$151 descontos</h4>
      </div>
    </div>
</div>

<div class="col s12 m6">
    <div class="card  blue lighten-1">
        <div class="card-action   blue darken-3 white-text">
          <span class="card-title"> Total Em Economia</span>
        </div>
      <div class="card-content white-text">
           <h4> R$5.215,00 Economía</h4>
      </div>
    </div>
</div>

<% end %>

app/views/shered/_search.html.erb
<h4>Pesquisar</h4>
<p></p>
<div class="row">


  <%= form_tag petshops_path, method: "get" do %>

  <div class="input-field col s8 m12">
    <%= text_field_tag :cidade, params[:cidade], placeholder:"Pesquisar cidade" %>

    <label for="cidade">Cidade:</label>
  </div>
  <div class="input-field col s6 m4">
    <i class="material-icons prefix">date_range</i>
    <%= text_field_tag :date, params[:date], class:"datepicker", placeholder:"Selecione uma data" %>
  </div>

  <div class="input-field col s6 m4">

    <select>
      <option value="" disabled selected>Selecione</option>
      <option value="1">Manhã</option>
      <option value="2">Tarde</option>

    </select>
    <label>Materialize Select</label>

  </div>

</div>

<button type="submit" class="btn blue lighten-2 waves-effect waves-lighten "> <i class="material-icons left">search</i>Buscar</button>

<% end %>
 