config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :animals
  resources :categories
  resources :petshops
  resources :descontos
  resources :agendamentos
  devise_for :users

  devise_scope :user do
    get "/store/:store" => "devise/registrations#new"
  end

  root to: "pages#welcome"

  get 'destroy-logo', action: :destroy_logo, controller: 'pages'
  resources :store_steps

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/petshop.rb
class Petshop < ApplicationRecord

belongs_to :user
has_one_attached :logo
validates :title, presence: true


# seach form
def self.search(search)
    if search
      where(["cidade LIKE ?","%#{search}%"])
    else
    all
    end
end





end

app/controllers/petshops_controller.rb
class PetshopsController < ApplicationController
  before_action :set_petshop, only: [:show, :edit, :update, :destroy]

  # GET /petshops
  # GET /petshops.json
  def index

    @petshops = Petshop.search(params[:cidade])

  end

  # GET /petshops/1
  # GET /petshops/1.json
  def show
  #authorize! :read, @petshop
  end

  # GET /petshops/new
  def new
    @petshop = Petshop.new
  end

  # GET /petshops/1/edit
  def edit
  end

  # POST /petshops
  # POST /petshops.json
  def create
    @petshop = Petshop.new(petshop_params)

    respond_to do |format|
      if @petshop.save
        format.html { redirect_to @petshop, notice: 'Sua loja foi adicionado com sucesso!' }
        format.json { render :show, status: :created, location: @petshop }
      else
        format.html { render :new }
        format.json { render json: @petshop.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /petshops/1
  # PATCH/PUT /petshops/1.json
  def update
    respond_to do |format|
      if @petshop.update(petshop_params)
        format.html { redirect_to root_path, notice: 'Sua loja foi atualizada com sucesso' }
        format.json { render :show, status: :ok, location: @petshop }
      else
        format.html { render :edit }
        format.json { render json: @petshop.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /petshops/1
  # DELETE /petshops/1.json
  def destroy

    @petshop.destroy
    respond_to do |format|
      format.html { redirect_to petshops_url, notice: 'Sua loja foi apagado do sistema' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_petshop
      @petshop = Petshop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def petshop_params
      params.require(:petshop).permit(:title, :address, :phone, :cep, :estado, :cidade, :descricao, :logo)
    end
end

app/helpers/petshops_helper.rb
module PetshopsHelper


require "correios-cep"

def ask_form

 

end

end

app/views/petshops/_form.html.erb
<%= form_with(model: petshop, local: true) do |form| %>
  <% if petshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(petshop.errors.count, "error") %> não foi possível de ser salvo:</h2>

      <ul>
      <% petshop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="input-field">
    <%= form.text_field :title %>
    <%= form.label 'Titulo' %>
  </div>


    <div class="file-field input-field">
      <div class="btn blue">
        <span><i class="material-icons white-text">image</i> Add Logo</span>
        <%= form.file_field :logo, autofocus: true, autocomplete: "logo", class:"validate" %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>

      <div class="input-field">
        <%= form.text_field :descricao %>
        <%= form.label :descricao %>
      </div>

  <div class="input-field">
    <%= form.text_field :cep %>
    <%= form.label :cep %>
  </div>

  <div class="input-field">
    <%= form.text_field :address %>
    <%= form.label :address %>
  </div>

  <div class="input-field">
    <%= form.text_field :estado %>
    <%= form.label :estado %>
  </div>
  <div class="input-field">
    <%= form.text_field :cidade %>
    <%= form.label :cidade %>
  </div>

  <h3>Contatos e Informações</h3>

  <div class="input-field">
    <%= form.text_field :phone, class: 'phone_with_ddd' %>
    <%= form.label :phone %>
  </div>




  <div class="actions">
    <%= form.submit class: "waves-effect waves-light btn green" %>
  </div>
<% end %>

app/views/petshops/edit.html.erb
<%= title('Petshop - Meu Negócio') %>

<!-- title editor  -->

<div class="col s12 m3">
<%=  select_menu()  %>
</div>

<div class="col s12 m9">
  <h1>Editar</h1>


  <%= render 'form', petshop: @petshop %>



</div>

app/views/petshops/index.html.erb
<%= title('Lista Petshop') %>


<div class="section"></div>
<% if flash[:notice] %>
<div id="notice" class="notify notify--success" role="alert">
  <strong><%= notice %></strong>
</div>
<% end %>
<!-- left col  -->

<div class="col s12 m3">
<%=  select_menu()  %>
</div>

 
  <div class="col s12 m9">
    <%= link_to '<i class="material-icons">add</i> Adicionar'.html_safe, new_petshop_path,
    class: "right btn btn-small waves-effect waves-light green"  %>

<%= render "shered/search" %>
<div class="section"></div>
    <ul class="collection">
    <% @petshops.each do |p| %>
      <li class="collection-item">

        <h4 class="title"><%= p.title %></h4>
        <h4 class="right red-text"><i class=" material-icons">local_offer</i></h4>
        <div class="row valign-wrapper">
          <div class="col s6">
            <%= image_tag ('https://picsum.photos/100/100/?image=57'),
              class: "left circle responsive-img" %>
          </div>

          <span class="right">

      <b>Adicionado em: </b><%= p.created_at.strftime("%a %d-%m-%Y") %>
    <p>     <%= truncate( p.descricao, length:180 ) %></p>
      <a class="btn waves-effect waves-light  blue " href="<%= root_url %>petshops/<%= p.id %>"><i class="material-icons left">launch</i> Acessar </a>
          </span>
        </div>

      </li>

      <% end %>



    </ul>

  </div>

app/views/petshops/new.html.erb
<div class="col s12 m3">
<%=  select_menu()  %>
</div>

<div class="col s12 m9">
<h1>Adicionar Novo</h1>

<%= render 'form', petshop: @petshop %>

<%= link_to 'Back', petshops_path %>

</div>

app/views/petshops/show.html.erb
<%= title(@petshop.title) %>
<div class="section"></div>

<!-- left col  -->

<div class="col s12 m3">
<%=  select_menu()  %>
</div>

<!-- col right -->

<div class="col s12 m9">

    <div class="row">
      <% if can? :update, @petshop %>
      <%= link_to '<i class="material-icons">edit</i> Editar'.html_safe, edit_petshop_path(current_user.petshop),
      class: 'btn waves-effect waves-blue right' %>

      <% end %>
    </div>


    <% if flash[:notice] %>
    <div id="notice" class="notify notify--success" role="alert">
      <strong><%= notice %></strong>
    </div>
    <% end %>

  <%= render "petshops/module/show" %>
</div>