config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :animals
  resources :categories
  resources :petshops
  resources :descontos
  resources :agendamentos
  devise_for :users

  devise_scope :user do
    get "/store/:store" => "devise/registrations#new"
  end

  root to: "pages#welcome"

  get 'destroy-logo', action: :destroy_logo, controller: 'pages'
  resources :store_steps

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user

 

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = current_user.animals.take(5)
   
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :age, :raca, :vacinacao, :sexo, :descricao, :user_id)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s12"><%= form.label :name %><% %><%= form.text_field :name %></div>

  <div class="input-field col s12">
    <%= form.number_field :age, in: 1...30 %>
    <%= form.label "Idade:" %>
  </div>

  <div class="input-field col s12">
    <%= form.text_field :dog %>
    <%= form.label 'Raça' %>
  </div>

  <div class="input-field col s12">
    <%= form.text_field :vacinacao %>
    <%= form.label :vacinacao %>
  </div>

  <div class="input-field col s12">
    <p>
        <label>
          <span>Mascolino</span>
          <%= form.check_box :sexo %>
        </label>
      </p>

  </div>

  <div class="input-field col s12">
    <%= form.text_field :descricao %>
    <%= form.label :descricao %>
  </div>

  <div class="input-field col s12">
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.label :user_id %>
  </div>
  <div class="fixed-action">
    <%= form.submit class: "btn waves-light waves-effect green darken-2" %>  <%= link_to 'Cancelar', animals_path, class: "btn-small waves-effect waves-light red lighten-1 right" %>

  </div>
<% end %>

app/views/animals/edit.html.erb
<%= title(" #{current_user.name} #{current_user.last_name} Editar"  ) %>


<div class="col s12 m3">


<%= render('layouts/parts/usernav') %>


</div> <!-- end left col -->

<!-- col right -->
<div class="col s12 m9">
  <h1>Editar</h1>

  <%= render 'form', animal: @animal %>

<div class="section"></div>
 
</div>

app/views/animals/index.html.erb
<% if flash[:notice] %>
<p id="notice"><%= notice %></p>
<% end %>

<div class="col s12 m3">
<%=  select_menu()  %>
</div>

<!-- col right -->


  <div class="col s12 m9">


      <span class="darken-text">
         <h4>Meus Pets</h4>

      </span>

<table class="striped">
<% if can? :create, Animal %>
 <a href="<%=  new_animal_path %>"   class="btn waves-light waves-effect"> <i class="material-icons">add</i> Adicionar</a>
<% end %>
<thead>
    <tr>
      <th data-field="id">Foto</th>
      <th data-field="name">Nome:</th>
      <th data-field="price">Raça:</th>
      <th data-field="price">Idade:</th>
      <th data-field="descricao">Descrição:</th>
      <th></th>

    </tr>
  </thead>

  <tbody>
<% @animals.each do |pet| %>
    <tr>

      <td><%= image_tag('https://loremflickr.com/320/240/dog', size: "150x150") %></td>
      <td><%= pet.name %></td>
      <td><%= pet.raca %></td>
      <td><%= pet.age %></td>
      <td><%= truncate(pet.descricao, leagh: 100) %></td>
      <td>
        <% if can? :update, Animal %>

          <a href="<%=  edit_animal_path(@animals) %>" class="btn waves-effect waves light green lighten-1"> <i class="material-icons">edit</i> </a>
          <% end %>
      <% if can? :destroy, Animal %>
          <%= link_to "<i class='material-icons'>delete</i>".html_safe, pet, method: :delete, data: {confirm: "Você realmente deseja deletar?", remote: true }, class: "delete btn waves-effect waves light red lighten-1" %>
        <% end %>
      </td>

    </tr>
<% end %>


  </tbody>
</table>

  </div>

app/views/animals/new.html.erb
<%= title(" #{current_user.name} #{current_user.last_name} Novo"  ) %>



<div class="col s12 m3">


<%= render('layouts/parts/usernav') %>


</div> <!-- end left col -->

<!-- col right -->
<div class="col s12 m9">
  <h1>Adicionar Novo</h1>

  <%= render 'form', animal: @animal %>

  <%= link_to 'Back', animals_path %>


</div>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>




  <div class="col s12 m3">


  <%= render('layouts/parts/usernav') %>


  </div> <!-- end left col -->

<!-- col right -->


  <div class="col s12 m9">


      <span class="darken-text">
         <h4>Meu Pet</h4>

      </span>

      <div class="row">
        <div class="col s12 m12">
          <div class="card">
            <div class="card-image">
              <img src="https://picsum.photos/800/300/?random">
              <span class="card-title">Title Pet Imagem 800 X 300 </span>
            </div>
            <div class="card-content">
              <p><h5> Name: <%= @animal.name %> </h5></p>
              <p><h6>Apelido: Tor</h6></p>
               <table>
                 <thead>
                   <tr>
                     <th data-field="id">Dados:</th>

                   </tr>
                 </thead>

                 <tbody>

                   <tr>
                     <td><b>Idade:</b> 5</td>

                   </tr>
                   <tr>
                     <td><b>Raça:</b> Rootwaller</td>

                   </tr>
                   <tr>
                     <td><b>Vacinação:</b> 1 </td>

                   </tr>
                   <tr>
                     <td><b>Sexo:</b> Macho</td>

                   </tr>
                   <tr>
                     <td><b>Descrição:</b> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus consequatur nulla quod natus maxime consequuntur at sapiente, porro mollitia praesentium dolorem,.</td>

                   </tr>
                 </tbody>
               </table>

            </div>
            <div class="card-action">
              <a class="btn green darken-3" href="#">Editar</a> |
              <a class="btn red darken-3" href="#">Deletar</a> | <%= link_to 'Edit', edit_animal_path(@animal) %> |
              <%= link_to 'Back', animals_path %>


            </div>
          </div>
        </div>
      </div>


  </div>
 